### ISSUE TITLE
CTHUB - Dev time with Justin

### ISSUE THREAD

**Issue by kcabhar** [bcgov/cthub#103]
List of data that users want to extract from TFRS:

• Credits of each supplier
• Debits of each supplier
• Category of credit transfers
• Totals of fuel supplied per year so we can easily compare volume changes on one page for a fuel supplier (and a prompt for the supplier to explain any changes in volume of 10% or more)
• What fuel suppliers have a rep agreement or are acting as an aggregator. For the aggregators, it would be great to have a list of their clients listed as well.
• What a fuel supplier owes for penalties (this would be my number 1 choice for these additions)
• A filter option of suppliers based on fuel type (electricity/liquid fuel etc.)
• When they began supplying (or first year joining TFRS)
• Highlight late report submissions per year (so any report for the year past the March 31st deadline)
• If a supplier wants their contact information to be published on our website for credit transfer buying or selling on their profile page.
•	How many suppliers reported electricity supply in a specific compliance period ( = how many electricity suppliers were there in a specific compliance period)
•	How much total electricity supply was reported per fuel class in a specific compliance period
•	How many compliance reports were submitted in a specific compliance period 
•	How many suppliers reported electricity supply in a specific compliance period ( = how many electricity suppliers were there in a specific compliance period)

Could Metabase also populate the “Fuel Supply” tab for each compliance period in the 2010 – 2022 Compliance Reporting Summary excel spreadsheet (EDRMS # D26453417F)? As in, would we be able to download this data and copy it into the “Fuel Supply” tab of the 2010 – 2022 Compliance Reporting Summary excel spreadsheet? This would eliminate the administrative task of copying the fuel supply information for each fuel type and class per supplier from each individual compliance report in TFRS and pasting it into this spreadsheet. 

The data needed for this per compliance period would be: 

Company
Fuel Type
Fuel Class
Provision of the Act relied upon to determine CI
Fuel Code or Schedule D (if applicable)
Quantity of Fuel Supplied
Units
CI Limit
CI Fuel
Feedstock (if applicable) 

Could Metabase also provide the below data for each supplier that submitted a compliance report in a specific compliance period? That’s the information that we manually copy from each individual supplier report in TFRS into a Company Overview excel spreadsheet for each supplier when processing the compliance report:

Compliance Year
Date Submitted
Number of FSE (this is not currently tracked in TFRS, so we can add it manually at this time)
Fuel Type
Fuel Class
Provision Code
Fuel Code
Fuel Quantity
Unit	Credits
Debits
YOY quantity of fuel (from previous compliance period, if this is not possible, we have a formula in the Company Overview excel template for this)
YOY # of FSE (this is not currently tracked in TFRS, so we can add it manually at this time

**Comment by Kailee-Douglas** [comment]
KD: I emailed 3 users to ask for a complete list of what data they want to extract from TFRS. Two users replied to date. There may be a few more users we can also ask for a more complete list.

•	Credits of each supplier
•	Debits of each supplier
•	Category of credit transfers
•	Totals of fuel supplied per year so we can easily compare volume changes on one page for a fuel supplier (and a prompt for the supplier to explain any changes in volume of 10% or more)
•	What fuel suppliers have a rep agreement or are acting as an aggregator. For the aggregators, it would be great to have a list of their clients listed as well.
•	What a fuel supplier owes for penalties (this would be my number 1 choice for these additions)
•	A filter option of suppliers based on fuel type (electricity/liquid fuel etc.)
•	When they began supplying (or first year joining TFRS)
•	Highlight late report submissions per year (so any report for the year past the March 31st deadline)
•	If a supplier wants their contact information to be published on our website for credit transfer buying or selling on their profile page.
