### ISSUE TITLE
CTHUB (LCFS) - Build Schedule B question query 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#106]
**Describe the task**
The purpose of this task is to develop a custom question/query in CTHUB that displays 'Schedule B' data from the TFRS dataset. This representation is crucial for each compliance period. It aims to distill the complex database structure into a more intuitive format for business users, enabling them to draw insights and generate subsequent queries with ease.

**Columns to include (left to right):**
- Organization Name
- Report ID
- Report Status
- Fuel type
- Fuel class
- Provision of the Act relied upon to determine CI (including description of provision, see below for more info)
- Fuel code or Schedule D (if applicable)
- Quantity of fuel supplied
- units 
- CI limit 
- CI Fuel
- Feedstock (if applicable, attached to the fuel code)
- EER fuel 
- Energy density
- Total energy
- Credits
- Debits

**Provision of the Act relied upon to determine CI:**
If possible (if stored in the database), we would like to show the description along with the actual provision of the Act for this column. 
- Section 6 (5) (a) - Prescribed carbon intensity
- Section 6 (5) (b) - Prescribed carbon intensity
- Section 6 (5) (c) - Approved fuel code
- Section 6 (5) (d) (i) - Default Carbon Intensity
- Section 6 (5) (d) (ii) (B) - Alternative Method
- Section 6 (5) (d) (ii) (A) - GHGenius Modelled

**Supplemental reporting:**
A potential issue may arise with supplemental reporting and showing duplicate data. If an organization has submitted a supplemental compliance report, we don't want this data set to show Schedule B entries for both the original report and the supplemental report. This duplicated information is not useful to the business area and would make it difficult to conduct analyses on the data. From the business area's perspective, a supplemental report **replaces** an original report. Therefore, we want this data set to only consist of the latest report for each organization for each compliance period; by latest, we mean latest status that is visible to IDIR users: submitted, reviewed/recommended by analyst or manager, Accepted (by Director), supplemental requested. Reports with the following statuses should be ignored: Draft, Rejected, Archived (deleted drafts).

See screenshot here for compliance reporting workflow: [Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1YwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb3df727eff329ddf71634bff2583944e2e10588/Compliance%20and%20Exclusion%20Reporting%20Workflow%202023-05-01%20%281%29.png)

Example, if an original report says the organization supplied 500 kWh of electricity and the supplemental report says they supplied 700 kWh of electricity. We want this data set to show one entry of 700 kWh of electricity. We don't want this data set to show two entries of electricity, one for 500 kWh and another for 700 kWh. When analyzing the data, this will give the wrong information in that it will look like the organization supplied 1,200 kWh of electricity when they only supplied 700 kWh.

**Purpose**
The current database structure is difficult for the business area to understand and therefore use to analyze data in ways needed to do their job. This task will enable the business area to understand key data and then be able to make their own queries/questions off of this data. 

**Acceptance Criteria**
- [ ] Comprehensive Data: The query should display all the specified columns in the mentioned order. Every header should be self-explanatory and should resonate with the underlying content.
- [ ] Data Integrity & Filtering: The data in each column should be accurate and specific to the compliance period. Ensure that the description and provision codes are present for the 'Provision of the Act' column. There should be no null values in required fields, and the results should be free from any duplicates or erroneous entries.
- [ ] Performance: The question/query, when executed, should not lead to any system lags or timeouts. Ensure that the query runs smoothly, taking into account the potential volume in the TFRS dataset.

**Additional Context**
- The creation of this query is driven by feedback from the business team about the challenges tied to the intricacy of the current database schema.
- After this query's establishment and validation, it will be a significant asset for the business team. They can use it as a model for subsequent queries or to derive more detailed insights.

**Screenshot of Schedule B:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBandOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2e2a3791b5cab210f66a7ddacc6189b67416baa7/Screenshot%202023-08-16%20Schedule%20B.png)

**Comment by AlexZorkin** [comment]
Query available here: https://metabase-prod.apps.silver.devops.gov.bc.ca/question/95-tfrs-schedule-b
