### ISSUE TITLE
CTHUB - Optimization of Schedule B Compliance Report SQL Query in Metabase

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/cthub#108]
### **Describe the task**
Optimize a comprehensive SQL query used to extract Schedule B information of the compliance report within Metabase. The optimization should focus on improving execution time and minimizing resource consumption, with special attention to subqueries and JOIN operations related to Schedule B information retrieval.

Link to the query: https://metabase-prod.apps.silver.devops.gov.bc.ca/question/95-tfrs-schedule-b

### **Purpose**
This SQL query is integral to Metabase for deriving insights from Schedule B of the compliance report, but its current performance is suboptimal. The task is crucial for enhancing the efficiency of Metabase questions that rely on this query, thereby improving user experience and ensuring timely and resource-efficient data retrieval specific to Schedule B information.

### **Acceptance Criteria**
- [ ] **Criteria 1:** The optimized query should demonstrate at least a 50% reduction in execution time compared to the current version.
- [ ] **Criteria 2:** The query must return accurate results, maintaining data integrity and consistency with the original query output, focusing on Schedule B information.
- [ ] **Criteria 3:** Any optimization implemented should adhere to existing coding and database standards and should not negatively impact other system functionalities or Metabase questions.

### **Additional context**
- Prioritize optimizations around the sections of the query pertaining to Schedule B, ensuring the precise and efficient extraction of related information.
- Consider the use of indexing, efficient subquery structuring, and data volume reduction techniques to specifically enhance the retrieval of Schedule B data.

### **Optimization Strategies**
1. **Focus on Schedule B Components:** Concentrate on refining subqueries, JOINs, and conditions related to Schedule B information, eliminating redundancies and optimizing related calculations.
2. **Appropriate Indexing:** Index the columns predominantly used in the retrieval of Schedule B information, such as those involved in JOIN conditions and WHERE clauses.
3. **Data Filtration:** Tighten WHERE clauses to filter out unnecessary data related to Schedule B at early stages of the query.
4. **Review Database Views:** Investigate leveraging or optimizing database views or materialized views associated with Schedule B to minimize computational overhead.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/cthub/108?planning-poker) with Zenhub @prv-proton

**Comment by justin-lepitzki** [comment]
Amazing optimization!
