### ISSUE TITLE
CTHUB - New fuel code columns for Schedule B query

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#109]
**Describe the task**
The business area has identified new columns to add to the Schedule B data query. 

These new column fields are all related to fuel codes:
- Feedstock Location
- Fuel Production Facility Location
- Finished Fuel Transport Mode

**Purpose**
User requested. Will enable additional data queries that are useful to the business area. Some examples include how much of the ethanol supplied in 2022 came from the US vs Canada? Where is most of the feedstock used to produce biodiesel coming from? 

**Acceptance Criteria**
- [ ] Prioritize optimizations around the sections of the query pertaining to Schedule B, ensuring the precise and efficient extraction of newly listed columns.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/cthub/109?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
