### ISSUE TITLE
CTHUB - GHGenius modelled Schedule B entries missing certain data fields

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#110]
**Describe the task**
Revise SQL query to resolve issues with missing data fields for Schedule B entries that use the 'GHGenius modelled' provision (i.e., *Section 6 (5) (d) (ii) (A) - GHGenius modelled* for the *Provision of the Act relied upon to determine CI*). 

Missing fields: 
- CI Fuel
- Credits/Debits

**Example entires in query**:
- ID# 10,809, 10,810, 10,811
- BC Ferries 2021 compliance report (report ID# 1103)

**Purpose**
The primary objective of this task is to address the missing data fields in Schedule B entries that utilize the 'GHGenius modelled' provision as outlined in Section 6 (5) (d) (ii) (A) of the Act. The absence of data in the fields "CI Fuel" and "Credits/Debits" hampers accurate reporting and compliance adherence in the example 2021 compliance report. By revising the SQL query, this task aims to ensure accurate and complete data retrieval, thereby facilitating better analysis and adherence to regulatory requirements.

**Acceptance Criteria**

1. Correct Data Retrieval: Ensure the revised SQL query retrieves and populates the missing fields for all Schedule B entries using the 'GHGenius modelled' provision.
2. Validation: Validate the data retrieved by the revised query against a reliable data source.
3. Performance: Ensure the revised query executes within an acceptable time frame without negative database performance impacts.
4. Documentation: Update relevant documentation to reflect the changes made to the SQL query and the data model.
5. Review: Have the revised query and data fields reviewed for correctness and compliance with the Provision of the Act.

**Additional Context**

- The GHGenius model assesses the life-cycle greenhouse gas emissions of transportation fuels. The missing data fields "CI Fuel" and "Credits/Debits" are crucial for accurate reporting in the BC Ferries 2021 compliance report.
- Previous attempts to resolve the issue were unsuccessful, indicating a possible deeper issue within the data model or database schema.
- Coordination with database administrators and the GHGenius model integration team may be necessary to fully resolve the issue.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/cthub/110?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton

**Comment by justin-lepitzki** [comment]
The CI Fuel value seems to be correct in some cases and incorrect in others. It is not clear why this is the case. Due to confidentiality concerns, examples will be provided outside of Zenhub.

**Comment by justin-lepitzki** [comment]
Tested with one issue identified; issue is likely related to #2667 fix. Will need to confirm once #2667 is on Prod; will create new card if there are still issues.
