### ISSUE TITLE
CTHUB - Schedule B query missing data fields 

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#112]
**Describe the task**
Investigate and revise SQL query for Schedule B to include full reporting data. currently the system is missing Schedule B entries from certain reports for certain compliance periods. 

**Examples of missing reports:**
- Suncor Energy Products Partnership: Missing 2019 & 2022 reports
- Parkland Refining (B.C.) Ltd.: Missing 2022 report
- Shell Canada Products & Imperial oil: Both missing 2020 & 2019 reports
- Consolidated Biofuels: missing 2021 report
- Cowichan Biodiesel Co-operative: missing 2019 report
- Federated Co-operatives Ltd.: missing 2020 and 2022 reports

**Purpose**
Resolve issues with missing data

**Acceptance Criteria**
- [ ] Modified query should retrieve all the latest compliance reports.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/cthub/112?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
