### ISSUE TITLE
CTHUB - Current Status column in Schedule B query showing 'Fuel Supplier Status' instead of 'Submitted'

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#113]
**Describe the task**
Revise the SQL query for the Schedule B question to display the 'Submitted' status in the 'Current Status' column for submitted reports. Currently, the status displayed is 'Fuel Supplier Status'. 

**Purpose**
Aligns with labels shown in the UI and business logic. 

**Acceptance Criteria**
- [ ] Query Revision: Modify SQL query to display 'Submitted' instead of 'Fuel Supplier Status' in the 'Current Status' column.
- [ ] Validation: Ensure the 'Current Status' column now shows 'Submitted' for all relevant entries.
- [ ] UI Alignment: Confirm UI reflects the updated status accurately.

**Comment by prv-proton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Low-Carbon-Fuel-Standard-644c2db3be098a001977ad0b/issues/bcgov/cthub/113?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton
