### ISSUE TITLE
CTHUB - Update to latest version of Metabase

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#118]
**Describe the task**
There is a new version of Metabase that includes new features. This task to update CTHUB's instance of Metabase to the latest version. 

**Purpose**
Users can take advantage of new features. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kuanfandevops** [comment]
The current release being used on cthub prod is v0.44.0. The latest available on dockerhub is  v0.47.6.

**Comment by justin-lepitzki** [comment]
Completed!
