### ISSUE TITLE
CTHUB - Create instance of Superset for testing

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/cthub#119]
**Describe the task**
Create an instance of Superset , connect to TFRS database, and grant access to team members. 

Link: https://superset.apache.org/

**Purpose**
So the team can test its functionality and compare it to Metabase.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kuanfandevops** [comment]
The official release on dockerhub is not published yet. We can try to use the latest.
