### ISSUE TITLE
CTHUB - Get Upload utility working again

### ISSUE THREAD

**Issue by airinggov** [bcgov/cthub#122]
**Title:** Get Upload utility working again

**Description:** The Upload utility is not functioning presently. Kuan had to restart Minio and Tim has to add users to have permission to use the upload function.
https://cthub-test.apps.silver.devops.gov.bc.ca/upload

But trying to use the original Excel data files isn't working. Clicking Upload doesn't show any feedback that anything has happened. Looking at Inspect shows a 500 error.

Excel files
https://bcgov.sharepoint.com/:f:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data%20and%20Report%20Samples?csf=1&web=1&e=Exq8fB

Metabase
https://metabase-test.apps.silver.devops.gov.bc.ca/auth/login?redirect=%2F

**Wireframe:** <link>

**Purpose and benefit to user:**
Getting the Upload function working would be a good step in kicking off the CTHUB project.

**Acceptance Criteria:**

- [ ] Given I am a IDIR CTHUB authorised user, When I am uploading a correct format data file, then it gets parsed into the CTHUB database visible through Metabase.

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by airinggov** [comment]
Hard to say what the exact files are because none of them are working. I tried to find the original cards that may have had them attached but couldn't locate them this way either. If it is easier you might just look at card 120 in the todo list

**Comment by tim738745** [comment]
From the CTHUB logs (test) :"Worksheet named 'Project_Tracking' not found"
