### ISSUE TITLE
CTHUB - Metabase: Write a Metabase question to compile ZEVA Supplier information

### ISSUE THREAD

**Issue by airinggov** [bcgov/cthub#135]
**Describe the task**
Write an SQL statement in Metabase (Question) to compile a dataset of ZEVA supplier data that brings information together from the multiple joined tables. Data should current information not draft or historical etc.

**Sample chart**
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0puQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d1d94f9395f08605eaef3f17fbbed99f9155fc3/analytics-1.png" alt="analytics-1.png" />

**Purpose**
This is to allow business area users of Metabase that don't have SQL knowledge or understand the ZEVA data model to easily generate visualizations with supplier data.

It may be worthwhile to have a session to review available data to determine which fields should be included.

•	Supplier ID
•	Legal Name
•	Common Name
•	Supplier Status
•	Supplier Class (Current)?
•	Credit Balance (current rollup of a/b total - 2 fields)?
•	First Model Year Report
•	Name of Representative
•	Street Address (Service address)
•	Address Other (Service address)
•	City (Service address)
•	Province/State/Region (Service address)
•	Country (Service address)
•	Postal/ZIP Code (Service address)
•	Street Address (Records address)
•	Address Other (Records address)
•	City (Records address)
•	Province/State/Region (Records address)
•	Country (Records address)
•	Postal/ZIP Code (Records address)

**Acceptance Criteria**
- [ ] create question in metabase that shows human readable information, that can be copied and reused by analysts

**Additional context**
- This Question will be joined to other questions to create charts and visualizations in Metabase.
- For reference, the developer can look at the "TFRS - Schedule B" question in the LCFS collection in metabase (prod). This results of this question acts as "base data" for other, simpler questions that can be created via the wizard by non-developers. For example, the "Fuel Supply Data" question (again in the LCFS question) was constructed using "TFRS -Schedule B".

**Comment by tim738745** [comment]
On metabase prod - in the "ZEVA Collection"; named "Supplier Information"

**Comment by airinggov** [comment]
Great, thanks Tim, I'll have a look next week
