### ISSUE TITLE
CTHUB - Metabase: Write a Metabase question to compile ZEVA ZEV model information

### ISSUE THREAD

**Issue by airinggov** [bcgov/cthub#136]
**Describe the task**
Write an SQL statement in Metabase (Question) to compile a dataset of ZEVA ZEV Model data that brings information together from the multiple joined tables. Data should be in a final completed state e.g. VALIDATED, not draft, submitted, historical etc.

**Purpose**
This is to allow business area users of Metabase that don't have SQL knowledge or understand the ZEVA data model to easily generate visualizations with organization data.

•	ZEV Model ID
•	Date Validated
•	Supplier ID
•	Supplier Common Name
•	Model Year
•	Make
•	Model
•	ZEV Type
•	US06 Test
•	EPA Range
•	Body Type
•	Weight
•	Vehicle Class
•	ZEV Class
•	Credit Entitlement
•	Validated
•	Active

**Acceptance Criteria**
- [ ] create question in metabase that shows human readable information, that can be copied and reused by analysts

**Additional context**
- This Question will be joined to other questions to create charts and visualizations in Metabase.
- For reference, the developer can look at the "TFRS - Schedule B" question in the LCFS collection in metabase (prod). This results of this question acts as "base data" for other, simpler questions that can be created via the wizard by non-developers. For example, the "Fuel Supply Data" question (again in the LCFS collection) was constructed using "TFRS -Schedule B".

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/136?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
