### ISSUE TITLE
CTHUB - Spike Research Data Structure for ICBC Data

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#145]
**Problem Description**  
ICBC data will be used by both CTHUB and ZEVA. ICBC data set is very large. We need to store clean VIN decoded data.
**In order to** use the ICBC data in both systems. ZEVA user has to have current data to validate credit applications. CTHUB users will need it to use it for a wide variety of analysis. 

**Solution Needs**
- Determine which data base the ICBC data will be stored, both Metabase and ZEVA will require access.
- Determine how the VIN decoder will run against raw ICBC data and stored to the data base.
- Will the VIN decoder run completely without user intervention?

**Timebox**
- How much effort are we committing to this research: 1 day of research

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- Presently ZEVA runs credit applications against only a subset of ICBC data but there could be benefit to using the full dataset (to include ICE) or larger dataset (filter out pre 2019). What are the potential impacts of this?
- might be good to include discussion with our data admin

-

**Comment by tim738745** [comment]
A potential solution:

(1) We can store ICBC vins in the database associated with the vin decoder (https://github.com/bcgov/vdcd)
(2) New ICBC vins can also be uploaded into said database via the frontend of the vin decoder.
(3) The vin decoder will run jobs periodically to decode the vins and store the results.
(4) Metabase can access the decoded vins by connecting directly to the database, and ZEVA may also call the vin decoder's api to get decoded vins.

Question: does an ICBC vin need to be marked as an ICBC vin, or can it be uploaded into the vin decoder like any other vin?

**Comment by kcabhar** [comment]
Clarification from Al: The only Vin that we are running through the decoder is the ICBC data.
