### ISSUE TITLE
CTHUB ITVR - Add ITVR Dashboard into Collection Menu Sidebar

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#148]
**Describe the task**
Add ITVR Dashboard into the collection menu situated on the sidebar of the application interface (CTHUB/Metabase). This addition will facilitate quicker access and navigation to the ITVR Dashboard for users.

**Purpose**
The purpose of this task is to enhance user experience and efficiency by providing direct access to the ITVR Dashboard from the collection menu. By integrating the dashboard into the sidebar, users can navigate to it without the need for additional clicks or steps.

**Acceptance Criteria**
- [ ] Add ITVR Dashboard link to the collection menu on the sidebar.

**Additional context**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/148?planning-poker) with Zenhub @emi-hi @tim738745
