### ISSUE TITLE
CTHUB ITVR - Hide Non-Relevant Tables in Metabase "Our Data Section"

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#149]
**Describe the task**
Hide or clean up tables within the "Our Data" section of CTHUB/Metabase to prevent users from seeing them, as they are not relevant and would likely cause confusion. See image below.

**Purpose**
The purpose of this task is to enhance user experience by removing visibility of tables that users would not understand.

**Acceptance Criteria**
- [ ] Identify tables in the "Our Data" section of Metabase that users are not expected to understand or find relevant.
- [ ]  Hide the identified tables from the user interface.
- [ ] Ensure that the hiding of tables does not affect the functionality of the ITVR dashboard.

**Additional context**
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm90QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d448d842728315e6bbe644691c73f4ec6af53e62/ITVR%20Tables%20Capture.JPG" alt="ITVR Tables Capture.JPG" />

**Development Checklist**
- [ ] in administration settings, under table metadata for ITVR, make all those not needed tables hidden

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/149?planning-poker) with Zenhub @emi-hi @tim738745
