### ISSUE TITLE
CTHUB - Model Year Report Showing Multiple Entries 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#160]
**Describe the task**
Model year reports in CTHUB are currently showing multiple entries for the same year and have different values except for the LDV sales.

**Purpose**
The purpose of this task is to address the presence of multiple entries for the same year in the reports, ensuring that only one entry is displayed for each year.

**Acceptance Criteria**
- [ ] One MY entry per supplier in CTHUB with correct information

**Additional context**
- The discrepancies in the model year reports is most likely due to the compliance obligation table pulling too many rows with outdated data.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/160?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
