### ISSUE TITLE
CTHUB - User Story - Security Model Deployment

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#161]
**Title:** Metabase Security Model 

**Description:** Initiate the deployment of the security model in CTHUB to enforce role-based access control (RBAC) and enhance data protection measures.

**Wireframe:** N/A

**Purpose and benefit to user:** Strengthen data security and streamline user access by defining clear roles and permissions within Metabase

**Acceptance Criteria:**  
We will get clarification from the business, that these roles will work for them.  
- [ ] Admin role: Only developers should have admin access and selected business team members who will also be responsible for managing user access. 
- [ ] Analyst/Engineering role: Users can create SQL questions based on models.
- [ ] Dashboard role: Users can create dashboards separate from SQL questions.
- [ ] Viewer role (internal): Access limited to internal government/IDIR users.
- [ ] Viewer role (external): Access available for the public.

**Development Checklist:**
- [ ] Create these roles/permissions within Metabase subject to what Metabase supports. If it comes up, another option is for each business area to have their own metabase instance.

**Notes:** 
The PO will check with the branch on which team members should have what access.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/161?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
This will be handled by implementing a materialized view. Closing this card.

**Comment by shayjeff** [comment]
This will be handled by implementing a materialized view. Closing this card.
