### ISSUE TITLE
CTHUB - Database/data changes as requested by metabase users

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#163]
**Describe the task**
We want to see the create/update user rather than 'SYSTEM'
SUVI date should be a date field rather than char

**Purpose**
to make the data more useable on metabase

**Acceptance Criteria**
- [x] Update and create user shows the idir as retrieved from public.user, will need to be written into the upload scripts
- [x] update SUVI table to hold date, include migration

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/163?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
