### ISSUE TITLE
CTHUB - put metabase models on git

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#164]
**Describe the task**
Investigate and set up a way to store metabase models on git

**Purpose**
Keeping our sql on git means we can have the same models on dev/test/prod

we can also use this to create views so that some fields are hidden from users

Michael Wells suggested using knex and provided us with a template of how he uses it
https://github.com/micheal-w-wells/db_migration_template

**Acceptance Criteria**
- [ ] set up knex or alternative
- [ ] add to readme to others can use it too

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/164?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
