### ISSUE TITLE
CTHUB - backend tests for upload script

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#165]
**Describe the task**
Write unit tests for the upload scripts in CTHUB.

**Purpose**
This is the core functionality of CTHUB and currently there aren't any tests for it.

**Acceptance Criteria**
- [x] Test for wrong cell types
- [x] Test for missing columns
- [x] Test for missing worksheet
- [x] Test for wrong number of rows for headers
- [ ] Test for user doesn't have permission

**Additional context**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/165?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
