### ISSUE TITLE
CTHUB - Replace whitelisted_users table with a user_permissions table

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#167]
**Describe the task**
Update cthub database. Create new table to contain user permissions instead of 'whitelisted_users'. 

**Purpose**
Whitelisted_users does not contain a field for permission type and the table name is not indicative of what it actually is. Something like user_permission is much more clear. We currently only contain user ids from keycloak and this is how users who can upload data are identified. We probably need a way to categorize users into upload, admin, etc, since some users should be able to insert uploaders themselves. 

**Acceptance Criteria**
- [x] Migration should be created that removes whitelisted_users and creates a new more clear table (details to be decided by Tim/team discussion)
- [x] another new table may need to be made that contains permission types 

**Development Checklist**
(1) The conventional way to do this would be to have a users table, a permissions table, and a table that is a product of these two tables that define what permissions users have.
(2) Should probably discuss with the team's data architect

**Additional context**
- [ ] We could create a new user entry each time a new IDIR user logs in, assuming anyone with a IDIR is allowed to log in.
- [x] We could also do a data migration to do the initial population of the permissions table

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/167?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
