### ISSUE TITLE
CTHUB - User permissions page

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#168]
**Title:**

**Description:**
-we need a page for setting user permissions. We need the user_permissions table to be done and to be storing names or something for an easier way to display users and select what permissions they have

**Wireframe:** <link>
https://preview.uxpin.com/a42f45b03540bc277cb03b7c5a178d9ea7ffd2fd#/pages/165706530?mode=m

Add User button adds IDIR name to list below alphabetically and in all caps, the user is saved with the Upload checkbox selected by default. No need to click Save below. Changing any of the check boxes requires a Save. Clicking the red X will delete the user completely but a modal will make the user confirm the deletion first.

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [ ] Given I am a user with the Admin permission, then I am able to see Admin feature (below the Upload feature) where I can edit user permissions (e.g. allow a user to upload). It can be made a separate page if this is preferable.

**Development Checklist:**
- [ ] Create a frontend page/components that users can navigate to and interact with to manage user permissions

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/168?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
