### ISSUE TITLE
CTHUB Bug - Get uploader working on test

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#169]
**Describe the Bug**
Uploader doesnt work on test due to minio issues

**Expected Behaviour**
Replace minio with object storage

**Actual Behaviour**
user gets a huge error message when they attempt to upload on test

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to cthub
2. Click on upload

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/169?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by tim738745** [comment]
No code changes; to peer-review this, please try the test environment to see if it's working.

**Comment by shayjeff** [comment]
Tested - Was able to upload a document successfully.
