### ISSUE TITLE
CTHUB - Refactor upload services

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#170]
**Describe the task**
We currently have several services for uploading datasets to cthub but we could just have one

**Purpose**
cleaner
less to maintain
easier to make changes

**Acceptance Criteria**
- [ ] one service is created for inserting records into database from excel file, passing arguments such as the model name, columns, cell types, etc 
- [ ] all references to other services are removed and replaced

**Additional context**
- this could be a good opportunity to clean up the spreadsheets, right now each one has a different worksheet it expects and number of 'header' rows but we could simplify and standardize them now?

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/170?planning-poker) with Zenhub @JulianForeman @tim738745 @emi-hi
