### ISSUE TITLE
CTHUB - Feedback During Excel File Upload

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#192]
**Title:** 
Providing Feedback During Excel File Upload

**Description:**
After users hit the upload button, implement a visual indicator to show them that an Excel file is being uploaded. Adding a visual indicator is essential to reassure users that their file is being processed.

**Wireframe:**

**Purpose and benefit to user:** 
- Users will see a clear sign that their Excel file is in the process of being uploaded.
- This feature reduces uncertainty during the file upload process, improving the user experience.

**Acceptance Criteria:**
- [ ] When users upload an Excel file, they should see a loading icon or animation indicating the file is being uploaded.

**Development Checklist:**
- [ ] add upload progress bar https://mui.com/material-ui/react-progress/

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/192?planning-poker) with Zenhub @emi-hi @JulianForeman
