### ISSUE TITLE
CTHUB - Save/Update Users on Admin Page

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#198]
**Describe the task**
 the frontend looks ready but currently is not saving users or permissions. We need to add create/update functionality on the backend and frontend 

**Purpose**
so that the admin user can add and update users

**Acceptance Criteria**
- [x] as an admin user
- [x] I can save new users and update existing user permissions
- [x] so that users can upload or make permission changes themselves

**Additional context**
we need to figure out the rules for removing admin permissions from users. Maybe a user cannot remove their own admin permission?

**Comment by shayjeff** [comment]
It looks great. The only thing is the red "x" is not able to delete a user. I'm not sure if this was requested. Would you like a new card created?  @emi-hi

**Comment by shayjeff** [comment]
Card 249 has been created for the "x" function.
