### ISSUE TITLE
CTHUB - Logout button

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#201]
**Describe the task**
logout button so the user can log out

**Purpose**
security 

**Acceptance Criteria**
- [ ] as a user
- [ ] when i click 'log out'
- [ ] i am logged out and have to re-enter my credentials to use the application

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/201?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested
