### ISSUE TITLE
CTHUB - page refinements

### ISSUE THREAD

**Issue by airinggov** [bcgov/cthub#210]
**Title:** CTHUB upload page refinements

**Description:**

- Change all case of ALL CAPS to be mixed case. The only content that should be ALL CAP is the list of IDIR user names
- Relocate success/error message bar to within the upload content box under the main heading, see wireframe
- Grey out / disable the upload box and two radio select buttons until the user selects a program from the list. Currently only the button is disabled but everything should be disabled until the selection is made.
- Similarly, hide the DOWNLOAD SPREADSHEET text until a program is selected and change the text to "Download Excel File (program data upload template)", see wireframe
- Sort IDIR user name list alphabetically

**Wireframe:** 
https://preview.uxpin.com/a42f45b03540bc277cb03b7c5a178d9ea7ffd2fd#/pages/165706530?mode=m

**Development Checklist:**
- [x] Sort IDIR names on backend before we hand them to the frontend.
- [ ] All caps that need to be changed to mix case are both buttons (download spreadsheet & browse to select)

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/210?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
