### ISSUE TITLE
CTHUB - Clear Upload Information on File Change 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#212]
**Title:** Clear Upload Information on File Change in CTHUB

**Description:** 
When a new file is selected for uploading in CTHUB any previously displayed upload information should be cleared, or the page should reset so that we can have a clean/new upload process. Please see images below to see what is currently happening: 

Uploaded ARC data: 
<img width="755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCs4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--920e9540524362691fa110c219fb07627e595229/image.png" alt="image.png" />

Then selected SUVI data and the ARC information is still visible: 
<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUM4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cc66fb726f69477b1dd1a66d726f8c2af32f83c/image.png" alt="image.png" />

**Wireframe:** 

**Purpose and benefit to user:**
This purpose is to prevent any confusion with the file upload. 

**Acceptance Criteria:**
- [ ] When I select a new file or dataset type after already uploading one, the banner displaying the previous upload information is removed.

**Development Checklist:**
- [ ] clear the error message when dataset type dropdown is changed or new file is added 

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/212?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
