### ISSUE TITLE
CTHUB - code formatting

### ISSUE THREAD

**Issue by tim738745** [bcgov/cthub#217]
**Describe the task**
We should agree on and install formatters for our source code.

**Purpose**
Best practice

**Acceptance Criteria**
- [ ] Agree on which formatters to use
- [ ] Install agreed formatters

**Additional context**
- ZEVA uses eslint for formatting js, but eslint has since deprecated their formatting rules in order to focus on linting (see https://eslint.org/blog/2023/10/deprecating-formatting-rules/#:~:text=We%20recommend%20you%20use%20a,semicolons%2C%20string%20formats%2C%20etc.). They recommend we use prettier (https://prettier.io/)
- Perhaps we could make formatting part of our workflows as well (see https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/)

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/217?planning-poker) with Zenhub @emi-hi @tim738745
