### ISSUE TITLE
CTHUB - Radio Button Positioning and Description Update

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#250]
**Describe the task**
Switch the positions of the radio buttons "Add to existing data"(move to top) and "Replace existing data" (move to bottom) and update the text descriptions. See mock-up below. 

**Purpose**
Preventative measures of accidental data loss by providing clearer guidance to users. 

**Acceptance Criteria**
- [x] The radio button for "Add to existing data" should now be positioned above "Replace existing data" and be checked by default
- [x] The text next to the "Add to existing data" radio button should read: "Add to existing data (default)."
- [x] The text next to the "Replace existing data" radio button should read: "Replace existing data (data cannot be restored, proceed only if you are certain that the new file contains all required data)."

**Additional context** 
https://preview.uxpin.com/a42f45b03540bc277cb03b7c5a178d9ea7ffd2fd#/pages/165706530

**Comment by tim738745** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/250?planning-poker) with Zenhub @JulianForeman
