### ISSUE TITLE
User Admin Page Refinements

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#255]
**Title:**
Just some things to make the user admin page nicer

**Acceptance Criteria:**

- [x] Given I am an admin, when i click add user and they are added the input box gets cleared

- [x] Given I am an admin when i add a new user to the user list they appear in the right place alphabetically? (check in with al on this)

**Development Checklist:**

- [x] Frontend changes as listed 
- [x] Move users container outside of upload container and have somewhere call both containers

**Notes:**

**Comment by tim738745** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/255?planning-poker) with Zenhub @JulianForeman
