### ISSUE TITLE
CTHUB - Temporary Hiding Downloads list in CTHUB

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#261]
**Describe the task**
Hide the select program download list in CTHUB until the business area submits the updated spreadsheets. Once updated, the spreadsheets will be added/visible in the drop-down menu and ready to be used to upload data. This will involve commenting out the lines that add them to the list temporarily.

**Purpose**
This task ensures that only updated spreadsheets are available for selection, maintaining data accuracy and integrity in CTHUB. By temporarily hiding the outdated downloads, users will not mistakenly use them for data upload. 

**Acceptance Criteria**
- [ ] The hidden downloads are not visible or selectable by users in the drop-down menu.
- [ ] Verify that only updated spreadsheets are available for selection once the task is completed.

**Additional context**
- The business area will be responsible for submitting the updated spreadsheets.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/261?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
