### ISSUE TITLE
CTHUB - Materialized Views for Pre-Filtering in Metabase 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#278]
**Problem Description**
**In order to** improve security and privacy within the database management system,
**a system or persona needs to** implement pre-filtering, generalization, and anonymization techniques on sensitive data before presenting it in Metabase.

**Solution Needs**
  - Pre-filtering of data using materialized views or alternative methods to remove sensitive information.
  - Generalization of data to maintain user usefulness while protecting privacy.
  - Anonymization of sensitive information such as names, addresses, and driver licenses.

**Timebox**
4 days

**Outcome**
Research successfully identified the need for implementing pre-filtering, generalization, and anonymization techniques to enhance security and privacy. Materialized views were explored as one option for pre-filtering data but other methods may also be suitable. 

**Additional Context**
Based on a request from the business area.  Please see write up for more information.  We will be comparing card 2155 with 278.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/278?planning-poker) with Zenhub @emi-hi @tim738745
