### ISSUE TITLE
CTHUB - compare materialized views/embedding metabase 

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#282]
**Problem Description** 
**In order to** come up with a plan moving forward with metabase, the devs should discuss the different solutions that have been researched

**Solution Needs**
- choose an option

**Timebox**
- How much effort are we committing to this research?

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- enter text here
- enter text here

**Comment by JulianForeman** [comment]
To put this simply after talking with all the devs. We are basically already creating materialized views in Metabase; neither of these will solve both problems, they each address some. Materialized views will allow us to anonymize data while maintaining usefulness for analytics. Embedding will allow us to control who can see/use which questions & dashboards and basically allow us to control roles/security but will require a paid plan.  Emily is going to reach out to Anton to see if there are any teams already using a paid version of Metabase so we can see how their experience has been.  Another option suggested by Tim is to instead spin up multiple Metabase instances that all connect to our database and then we can seperate who from each team can log into each of those. This will require another converstaion with the business area to figure out if that's a viable approach; but it would likely be the easiest solution.
