### ISSUE TITLE
CTHUB - Go Electric Rebates (GER) File Upload

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#283]
**Describe the task**
Add the updated Go Electric Rebates (GER, formerly SUVI) file to CTHUB.

**Purpose**
The purpose is to enable the business area to commence uploading data.

**Acceptance Criteria**
- [ ] Address pre-processing requests.
- [ ] Update SUVI model to now be GER model
- [ ] Update *GER* model if needed, to contain all necessary columns
- [ ] Update constants to reflect new model & data format
- [ ] Update frontend to use GER instead of SUVI
- [ ] Test data upload

**Dev Checklist**
- [ ] Address any remaining issues with refactored uploader or new error displays

**Additional context**
I've copied the folder with all the information from the business area to our TEAMs channel: https://bcgov.sharepoint.com/:f:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/GER_shared_with_Agile_team?csf=1&web=1&e=twtf24

- GER_format_for_CTHub.xlsx contains detailed descriptions of field types, missing values, possible values, errors, warnings, and pre-processing requirements.
- SUV-GER_Master_Distribution_List.xlsx serves as the original dataset for testing upload requests.
- GER_notes_for_Agile_team.html outlines pre-processing requests, with Sections 1-2 being straightforward and Sections 3-6 requiring further discussion for feasibility.
- SUV-GER_Master_Distribution_List_clean.xlsx is the cleaned version of the dataset, pending upload to Metabase after updating headings.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/283?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
New requirements have been identified by the business area. This card will be closed, and new cards will be created to address the additional requirements.
