### ISSUE TITLE
CTHUB - move vdcd stuff into cthub project

### ISSUE THREAD

**Issue by tim738745** [bcgov/cthub#284]
**Describe the task**
Move the stuff in https://github.com/bcgov/vdcd to https://github.com/bcgov/cthub, subject to considerations.

**Purpose**
Originally, I thought it would be cleaner to have the vin decoding stuff as a separate project, but users may want, in metabase, to join decoded vin data with other data in CTHUB, so the vin decoder and cthub should be contained within the same application.

**Acceptance Criteria**
- [ ] It was discussed that the decoded vin information should never change; we should remove the "upload of previously uploaded vin triggers a fresh decode" feature in https://github.com/bcgov/vdcd.
- [ ] - [ ] The contents (or most of the contents) in https://github.com/bcgov/vdcd should be moved to https://github.com/bcgov/cthub, and should run as before; some modifications/omissions here and there would probably be necessary (e.g. updating paths, excluding certain classes, etc.)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/284?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Will test when Kuan is finished his dev ops work.

**Comment by tim738745** [comment]
@shayjeff I think you can test this in metabase dev now; you can have a look at the "Vpic Decoded Vin Record" table in the CTHUB database
