### ISSUE TITLE
CTHUB - store data alongside uploaded vins

### ISSUE THREAD

**Issue by tim738745** [bcgov/cthub#285]
**Title:**
CTHUB - store data alongside uploaded vins

**Description:**
An upload of vin data (ICBC data) can contain other columns (e.g. make, model); we should store the information in these other columns.

**Wireframe:** <link>

**Purpose and benefit to user:**
This is something users may find useful

**Acceptance Criteria:**

- [ ] Given I am a user, when I upload a spreadsheet containing vins and data associated with those vins, all the data is stored.

**Development Checklist:**
- [ ] Update the UploadedVinRecord model to store data from other fields; we can look at how the DecodedVinRecord model stores data that are not vins.

**Notes:**
It was discussed that a vin may not be uniquely associated with an uploaded vin record; further information to come as to which fields (vin + ?) form a unique constraint.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/285?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Will test when Kuan is finished his dev ops work.

**Comment by tim738745** [comment]
@shayjeff I think you can test this in metabase dev now; you can have a look at the "Uploaded Vin Record" table in the CTHUB database
