### ISSUE TITLE
CTHUB - vinpower microservice

### ISSUE THREAD

**Issue by tim738745** [bcgov/cthub#300]
**Title:**
vinpower microservice

**Description:**
Integrate ESP data's vinpower Java product into CTHUB as a spring microservice - can use ITVR's spring microservice as a template.

**Wireframe:** <link>

**Purpose and benefit to user:**
This will allow users to use decoded vin information that was obtained using vinpower.

**Acceptance Criteria:**

- [ ] Given I am a developer, I can RESTfully call this microservice with VINs and have it return the decoded information.

**Development Checklist:**
- [ ] Integrate ESP data's vinpower Java product into CTHUB as a spring microservice - can use ITVR's spring microservice as a template.

**Notes:**
Will receive the jar file from ESP data on Monday, May 20, 2024 - will update card then.
Edit - will receive the jar file on Monday, May 27, 2024.

**Comment by shayjeff** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/300?planning-poker) with Zenhub @tim738745 @emi-hi @JulianForeman

**Comment by shayjeff** [comment]
This card is blocked until we receive the Java file. The file should be available next week Monday. The BA will let us know once they get it.

**Comment by shayjeff** [comment]
Received data.
