### ISSUE TITLE
CTHUB - Fix Undefined Upload Error on Dev 

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#301]
**Describe the Bug**
Uploader on dev is giving an undefined error even when it runs correctly locally

GER dataset

**Expected Behaviour**
datasets should be uploaded with no issues

**Actual Behaviour**
gives an error when uploading (says undefined)

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
5

**Dev Notes**
Originally this seemed to be an issue specifically on dev probably to do with user permissions. On testing locally I couldn't reproduce this with 100% correct spreadsheet upload.  So probably a good idea to pull in the dev database and test with a valid spreadsheet and also invalid spreadsheet(s).

**Comment by tim738745** [comment]
@shayjeff There doesn't seem to be any issues with uploading GER data or ICBC data on CTHUB dev; if you're still running into issues when testing please call me into the testing session and we can work through it together!

**Comment by tim738745** [comment]
@katerinkus could you please send me the GER data that you tried to upload but had an error with so I can take a look? Thanks!

**Comment by katerinkus** [comment]
Sure! I will follow up on Teams, @tim738745

**Comment by tim738745** [comment]
Issue was how certain columns in the spreadsheet were expected to be named a certain way; this was addressed in cards 312/307, or PR number 330.
