### ISSUE TITLE
CTHUB - redirect to login page after timeout

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#304]
**Describe the task**
If keycloak has timed out and the user cannot do anything in the application anyways, redirect them to the login page

**Purpose**
makes the user experience better if they are aware when they have been logged out

**Acceptance Criteria**
- [ ] as a CTHUB user, after keycloak times out, I am redirected to the login page so when i am ready to use the application i am aware i've been logged out and have to log in to continue

**Note**
ZEVA has similar functionality, check how it is done there

**Comment by ArawuSamuel1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/304?planning-poker) with Zenhub @emi-hi

**Comment by ArawuSamuel1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/304?planning-poker) with Zenhub @tim738745

**Comment by shayjeff** [comment]
Tested - Was redirected to the login page.
