### ISSUE TITLE
CTHUB - GER Upload Naming Scheme

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/cthub#307]
**Describe the task**
Create a preparation function for the GER uploader that alters specific values in the Manufacturer and Applicant Name columns.

**Acceptance Criteria**
- [x] Any value with a variation of 'Limited' should be returned as Ltd.
- [x] Any value with a variation of 'Incorporated' should be returned as Inc.

**Additional context**
- Please see GER notes 1.2 the GER_Notes file located in our shared CTHUB teams folder. Katia provided lots of reference code and more detailed instructions.
https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/307?planning-poker) with Zenhub @emi-hi @tim738745
