### ISSUE TITLE
CTHUB - Refine how we write the ICBC file data to the database

### ISSUE THREAD

**Issue by tim738745** [bcgov/cthub#310]
**Title:**
Refine how we write the ICBC file data to the database

**Description:**
We should refine how we write the contents of the ICBC file to the database to take into account user requirements regarding how we treat records that have the same vin but different postal codes.

**Wireframe:** <link>

**Purpose and benefit to user:**
This is a requirement.

**Acceptance Criteria:**

- [ ] Given I am a cthub uploader, when I am uploading an ICBC file, then new records in the file are inserted into the database, and updated records in the file are updated in the database. A new record is defined to be a record whose (vin, postal_code) values don’t exist in the database, and an updated record is a record whose (vin, postal_code) values do exist in the database.

**Development Checklist:**
- [ ] We can try to use the “update_conflicts” argument of the Django querset API if we update to Django 4.2 (see https://docs.djangoproject.com/en/4.2/ref/models/querysets/#bulk-create); otherwise we’ll have to write code that decides which records to bulk insert and which ones to bulk update, while watching our memory usage (see https://docs.python.org/3/library/tracemalloc.html#tracemalloc.get_traced_memory)
- [ ] We should assume that an ICBC file may have multiple records with the same (vin, postal_code) pair, and we should only use the one with the most recent snapshot_date to do a database insert/update (this will necessitate pulling in all the vin and postal code values in the file; please keep in mind the possibility of memory leaks when doing this!)

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/310?planning-poker) with Zenhub @emi-hi @tim738745
