### ISSUE TITLE
CTHUB - Make Value/Cell Casing Consistent

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#312]
**Task Description**
Create a preparation function for the GER upload (potentially all uploads, ask Katia about this) that keeps the value of each column's capitalization consistent.

**Purpose**
It makes it more readable and also allows for us to better check what is inside a cell in the future for duplicates/naming schemes etc...

**Acceptance Criteria**
- [ ] The read/returned values should all be capitalized the same way

**Development Checklist**
- [ ] Create either a re-usable preparation function for specifically GER or write it into the actual uploader to capitalize values the same way.

**Additional context**
Please see GER Notes 1.1 located in the GER_Notes file contained in the shared CTHUB folder in Teams. https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ

We can use built in functions to make everything capitals or lowercase or title structure so this shouldn't be much work.

**Comment by shayjeff** [comment]
Copied info from card # 2176 because it was opened under ZEVA not CTHUB.

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/312?planning-poker) with Zenhub @emi-hi @tim738745
