### ISSUE TITLE
CTHUB - GER/SUVI Consistent prepositions and articles

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#316]
**Describe the task**
Fix formatting issues in `Applicant Name` and `Manufacturer` column values in the GER/SUVI dataset. 

When "BC" is used in the context of a name, it should be "BC", e.g. "BC Cider". But when it is next to the word "Ltd."), it should be "B.C. Ltd.". "And" should be "and", and "Of" should be "of" and "The" should be "the" (same for "A" and "An").

**Purpose**
This task fixes formatting inconsistencies that are a result of changing column values to be sentence case or upper case. For instance, `Bc Cider And Juice`  would become `BC Cider and Juice`, `The Best Company Of 2020 Bc Ltd.` would become `The Best Company of 2020 B.C. Ltd.`.

**Acceptance Criteria**
this code is in the jupyter file:
- [x] `Bc Ltd.` becomes `B.C. Ltd.`
- [x] `Bc` becomes `BC`
- [x] `Of` becomes `of` if it is not the first word in the string.
- [x] `And` becomes `and` if it is not the first word in the string.

Write our own code for these ones:
- [x] `The` becomes `the` if it is not the first word in the string.
- [x] `A` becomes `a` if it is not the first word in the string.
- [x] `An` becomes `an` if it is not the first word in the string.

**Additional context**
Please see [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), section 1.3 for some regex ideas.

There are ~150 prepositions (e.g. _under_, _at_), etc. so if would be too difficult to do all of them without knowing the context. That is why preposition "of",  articles and "and" is enough.

**Comment by ArawuSamuel1** [comment]
Thank you @katerinkus 
This is pretty clear even as a non dev i can understand what to want done in this task. 

We would discuss more in refinement to see of the devs have any questions.

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/316?planning-poker) with Zenhub @emi-hi @tim738745
