### ISSUE TITLE
CTHUB - GER Adjust manufacturer names

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#317]
**Describe the task**
Since all `Manufacturer` column values are set to sentence case for consistency, some manufacturer names end up formatted incorrectly. For instance, "Lightning Emotors" should actually be "Lightning eMotors". The following values should be adjusted:
 - `International Ic Bus` -> `International IC Bus`
 - `Lightning Emotors` -> `Lightning eMotors`,
 - `Avro Gse` -> `Avro GSE`,
 - `Bmw` -> `BMW`,
 - `Ego` -> `EGO`,
  - `Sc Carts` -> `SC Carts`

**Purpose**
To display properly formatted manufacturer names.

**Acceptance Criteria**
- [ ] All values in the list are properly formatted according to the specifications above.

**Additional context**
Please see [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), section 1.4 for to grab a python dictionary with the values above.

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/317?planning-poker) with Zenhub @emi-hi @tim738745
