### ISSUE TITLE
CTHUB - GER Coerce strings to numeric in numeric columns

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#320]
**Describe the task**
Coerce strings in numeric columns ('Max Incentive Amount Requested', 'Incentive Paid', 'Total Purchase Price (pre-tax)') to numbers by removing white spaces and commas. If the value in the cell is still not numeric after that, user should get an error telling them the row and the column name to fix it.

This method should be generalized to other datasets to convert strings to numeric.

**Purpose**
To fix common issues in numeric columns that prevent pandas from seeing values as numbers.

**Acceptance Criteria**
- [ ] Commas are removed automatically (e.g. `1, 500` needs to be `1500`)
- [ ] White spaces are removed automatically (e.g. "   40" needs to be "40")
- [ ] An error should come up if a cell value is still not numeric after that with the row index and column name.

**Additional context**
- Since the Vehicle & Industry team area are using excel, the index of the row will be plus 2 since in excel headers are in row 1, and data starts in row 2 while pandas start counting rows at 0 by default.
- Please find and example attached in [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), Section 2.1.

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/320?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested
