### ISSUE TITLE
CTHUB - GER phone number validation

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#325]
**Describe the task**
GER dataset contains phone numbers in the `Phone Number` column that could be anywhere from Canada. The number of digits should be 10 but it could have different formats (dashes, brackets, etc.). Optionally, the first three numbers should be checked against Canada's area codes to make sure they are valid. A warning should come up if a number is incomplete or has a non-existing area code.

**Purpose**
It ensures that we have proper contact information.

**Acceptance Criteria**
- [x] Warning comes up if the number of digits is not 10 with the row index and the problematic phone number
- [x] Warning comes up if the area code does not exist with the row index and the problematic phone number (optional, it is not easy to find a good area code dataset)

**Additional context**
- Please see [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), section 6 for some regex ideas.
- Useful [resource](https://nationalnanpa.com/index.html) with area codes (but it is a bit confusing)

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/325?planning-poker) with Zenhub @emi-hi @tim738745

**Comment by shayjeff** [comment]
Tested
