### ISSUE TITLE
CHTUB - GER Notes column and tab name

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#326]
**Describe the task**
Add `Notes` column to GER headers. Notes can contain missing values. Replace Main list tab name with Distribution List - Master. This is the final name.

**Purpose**
Allow the team to add short notes to their records.

**Acceptance Criteria**
- [x] `Notes` column that can contain ~ 5 sentences. (allow blanks and nulls 250 chars).
- [x]  Update code to ingest notes column from spreadsheet and add to database.
- [x]  Tab name is Distribution List - Master

**Additional context**
We explained to the team how the upload works. They now know that the tab name should not be changed unless it is very necessary and the Product Owner is notified.

**Comment by katerinkus** [comment]
Moved to 326

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/326?planning-poker) with Zenhub @emi-hi @tim738745
