### ISSUE TITLE
CTHUB - GER Typo checker for Applicant Name

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#328]
**Describe the task**
`Applicant Name` column is inconsistent. For instance, "ABC & Company" could also be spelled "ABC and Co". Understanding which spelling or name is correct is impossible without human judgment.  The person uploading a dataset should get a warning message (before the dataset is finally uploaded). This warning message should contain a list of lists of values that are very similar, indicating that it is possible the same person/entity. From there the user can work on their spreadsheet to fix issues and try uploading again. The user should also have an option to ignore this message and proceed to upload regardless.

**Purpose**
It normalizes the data for easier retrieval and proper groupings.

**Acceptance Criteria**
- [x] Similar sounding names are displayed to the user in a warning before the final upload
- [x] User can ignore the warning and proceed to the upload
- [x] section 3 of notes has function that can be used but it should be tested more to ensure it catches all issues
- [x] do all processing before trying any insert and pop up alert at the end if warnings are caught and user will have to choose to proceed or cancel. if the user cancels then no records get inserted and the user can make changes to their spreadsheet before proceeding. If they proceed it inserts the records.

**Additional context**
- Please see [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), section 3 for my implementation using python library [difflib](https://docs.python.org/3/library/difflib.html)

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/328?planning-poker) with Zenhub @emi-hi @tim738745

**Comment by shayjeff** [comment]
Tested
