### ISSUE TITLE
Bug: Replace data not working

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#355]
**Describe the Bug**
when you click replace data it no longer replaces it but adds to it

**Expected Behaviour**
it should delete the old data and replace it

**Actual Behaviour**
when you click replace data it no longer replaces it but adds to it

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:

**Comment by katerinkus** [comment]
Tested it with the GER data and it works ✨!
