### ISSUE TITLE
Bug - geographic names maximum query length

### ISSUE THREAD

**Issue by emi-hi** [bcgov/cthub#361]
**Describe the Bug**
if the spreadsheet contains too many geographic locations the api request fails

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: uploader
1. upload the suvi dataset from teams
the backend shows this error: Client Error: Request-URI Too Long for url

this indicates we need to change the way the request is sent, eg batches

**Comment by JulianForeman** [comment]
PR up for this does address the maximum query length, but I found when testing on a huge file it takes FOREVER to load. Maybe we should discuss this api call further.
