### ISSUE TITLE
CTHUB - GER Uploader Failing

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/cthub#379]
**Describe the Bug**
Uploading GER data is now failing in CTHUB

**Expected Behaviour**
The uploader should either successfully upload the file or display the errors and warnings associated with it to the user so it can be corrected.

**Actual Behaviour**
The upload fails and just displays a generalized error message.

**Implications**
GER data cannot be uploaded or tested.

**Comment by katerinkus** [comment]
Checked and it is all good now! I was able to upload a test file :)

**Comment by katerinkus** [comment]
Tried with a larger file and it is an issue, unfortunately.

**Comment by katerinkus** [comment]
It failed once and worked another time. I will leave it as is for now and bring it up if it fails again.
