### ISSUE TITLE
CTHUB - new database for ds and engineering needs

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#387]
**Describe the task**
Data scientists need to have an option to add their data into OpenShift without having to use the CTHub upload tool.

**Purpose**
Currently, one of the projects is generating gigabytes of data that the data scientist is accessing locally using PostgreSQL. Our only storage option is on LAN which is not useful for this type of work. A database on OpenShift would be a solution to this problem.

**Acceptance Criteria**

- [ ] CRUD permissions for a new database

**Additional context**
This database may also be eventually connected to DAP (with PIA's in place) to use with PowerBI or other dashboarding tools.

**Comment by kuanfandevops** [comment]
Created ds-test-crunchy-ds cluster on Zeva Test. @katerinkus DS can login through terminal and give a try.

**Comment by kuanfandevops** [comment]
This is done
