### ISSUE TITLE
CTHUB - Missing column and/or sheet error

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#398]
**Describe the task**
Create an error message that notifies the user that a column is missing. The same should happen if the sheet is missing. The sheet error should take priority (since there would be no columns to read without a sheet). 

**Mockups**
Flow File Upload Failed - Column missing https://www.figma.com/design/K7gNHRnlYuG27w8XGVquY5/Warnings%2FErrors?node-id=479-300&t=2No47FnRznfaQwRh-1 
Flow File Upload Failed -  Sheet is missing https://www.figma.com/design/K7gNHRnlYuG27w8XGVquY5/Warnings%2FErrors?node-id=585-2725&t=2No47FnRznfaQwRh-1 

**Prototype** 
Flow File Upload Failed - Column missing https://www.figma.com/proto/K7gNHRnlYuG27w8XGVquY5/Warnings%2FErrors?page-id=0%3A1&node-id=585-1906&node-type=frame&viewport=1489%2C-616%2C0.09&t=h6jNoPFxt0JzfIn6-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=585%3A1906 
Flow File Upload Failed -  Sheet is missing https://www.figma.com/proto/K7gNHRnlYuG27w8XGVquY5/Warnings%2FErrors?page-id=0%3A1&node-id=585-2727&node-type=frame&viewport=1489%2C-616%2C0.09&t=h6jNoPFxt0JzfIn6-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=585%3A2727 

**Purpose**
We provide users with a template for dataset uploads, which they can use either to align their own dataset’s column names or create a new dataset based on the template. The system needs to check for the presence of all required columns when a dataset is uploaded. If a column is missing, the system should display an error message indicating which column(s) are missing.
Additionally, the system should first validate the name of the sheet before checking for any missing columns. If the sheet name does not match the expected template, the upload should fail without proceeding to the column validation step.

**Acceptance Criteria**
Sheet Name Validation
- [x] If the user has renamed the sheet in the dataset, the upload should fail because the system checks for the correct sheet name first, before checking for any missing columns.
File is missing worksheet 'sheet_name'. A worksheet with this name is required to proceed with the upload.
"File Upload Failed - The sheet name doesn't match the required “Sheet name” 
Please rename the sheet to the required “Sheet name” before next upload."

Missing Columns:
- [x] If the sheet name is correct but one or more required columns are missing, the system should display an error message specifying the missing column(s).
"File Upload Failed - Missing one or more required columns
Your file has been processed and column "'Economic region' is not found in the dataset. Please ensure that your dataset matches the provided template, and that all required columns are present. You can download the template for reference. Once corrected, you can upload your file again."

Highlight Failed Upload
- [x] In case of an error related to either the sheet name or missing columns, the uploaded file name should be highlighted in red, with the text “Failed upload” displayed below upload section. 

General Error Flow
- [x] The system must prioritize checking the sheet name before validating the columns. If the sheet name is incorrect, the column validation should not occur.

**Comment by tim738745** [comment]
@katerinkus and @shayjeff: while planning to implement these changes, I noticed that there are already checks for missing sheets and columns, and critical errors are displayed in cases where those things are missing. I just want to confirm that this card supersedes the way we currently deal with missing sheets/columns?

**Comment by katerinkus** [comment]
@tim738745 and @shayjeff I took a look on dev and yes, the error works but the front-end does not match the mock up. I think it existed originally but it does not work well from the UX perspective. For instance, it talks about rows in the warnings while the message should be about column names and sheet names. Column name is good to go to be reworked to match the mockup but the sheet name, not yet, because I was asking Lalita if we should include the actual sheet name in the error message. It appears in the pop-up but it is not displayed again and is referred to as "Sheet name" instead of the actual name.

**Comment by shayjeff** [comment]
Card #433 was created for the deletion of the old notification.
