### ISSUE TITLE
CTHUB - Upload Header/Spreadsheet Error Not Displaying

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/cthub#400]
**Describe the Bug**
The CTHUB uploader does not provide a descriptive error when a sheet that is missing or is missing headers.

**Expected Behaviour**
When uploading a spreadsheet that is missing or has missing or incorrect headers, an error should be displayed to the user that describes the issue.

**Actual Behaviour**
A generic "An error occurred" message is displayed.

**Implications**
Users will have no idea why the upload is failing or how to fix it.

**Steps To Reproduce**
Create/Modify spreadsheet that has an incorrect name or missing/incorrect header names
Login to CTHUB
Upload spreadsheet
See generic error

**Comment by katerinkus** [comment]
All good, I saw the right message.
